apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api-app
spec:
  selector:
    matchLabels:
      name: api-app
  replicas: 1
  template:
    metadata:
      labels:
        name: api-app
    spec:
      containers:
      - name: api-app
        image: epochdemo/epoch-sample-api:master.20210817-174219
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: FLASK_ENV
          value: "development"
        - name: API_PORT
          value: "8000"
        - name: PYTHONIOENCODING
          value: utf-8
        - name: TEST_ENV
          value: >-
            ""
            ""
            ""
            ""
            ""
            ""
            ""
            ""
            ""
            ""
            ""
            ""
            ""
            ""
            ""
            ""
            ""
  strategy:
    blueGreen:
      activeService: api-app-bluegreen-active
      previewService: api-app-bluegreen-preview
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 120

---
apiVersion: v1
kind: Service
metadata:
  name: api-app-bluegreen-active
  labels:
    name: api-app-bluegreen-active
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 
  selector:
    name: api-app

---
apiVersion: v1
kind: Service
metadata:
  name: api-app-bluegreen-preview
  labels:
    name: api-app-bluegreen-preview
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 
  selector:
    name: api-app
